server:
  port: 8082

spring:
  redis:
    #    host: 192.168.92.128
    host: 127.0.0.1
    port: 6379
    password:
    database: 0
    timeout: 10000ms
    lettuce:
      pool:
        # 最大连接数，默认是8
        max-active: 1024
        # 最大连接阻塞等待时间，默认-1
        max-wait: 10000ms
        # 最大空闲连接
        max-idle: 200
        # 最小空闲连接
        min-idle: 5
  # 邮件配置
  mail:
    # 邮件服务器地址
    host: smtp.163.com
    # 协议
    protocol: smtp
    # 邮编格式
    default-encoding: utf-8
    # 授权码（在邮箱开通服务时获取）
    password: CXOIAZKALKGLRCJP
    # 发送者邮箱地址
    username:  ht19950917@163.com
    # 端口（不同邮箱不同端口）
    port: 25
    # rabbitmq配置
  rabbitmq:
    username: guest
    password: guest
    host: 127.0.0.1
    port: 5672
    listener:
      simple:
        # 开启手动确认
        acknowledge-mode: manual